name: Deploy backend
on: [push]
#  pull_request:
#    types: [closed]

jobs:
  build:
    name: Deploy backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
      working-directory: ./backend
    - run: yarn sls deploy
      working-directory: ./backend
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
